# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: datawarehouse
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./exercises/exercise_06/datawarehouse/data/stores-and-products.sql:/docker-entrypoint-initdb.d/stores-and-products.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"