services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    ports:
      - "5432:5432"
    volumes:
      # init script
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql