services:
  db_data_source:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: data_source

    ports:
      - "5432:5432"
    volumes:
      # init script
      - ./data/stores-and-products.sql:/docker-entrypoint-initdb.d/init.sql

  db_data_warehouse:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: data_warehouse

    ports:
      - "5433:5432"
    